### PR TITLE
 feat: add 'connectedToInput' @input property and fix the build

### PR DESCRIPTION
**Pull request by Tian-Hun**

### CODE REVIEW

**Comment by Agranom** [comment]
I'm not sure that we need this feature, because the timepicker shows up as popup with overlay, so why do we need to stick it to input?

**Comment by Tian-Hun** [comment]
> I'm not sure that we need this feature, because the timepicker shows up as popup with overlay, so why do we need to stick it to input?

According to @angular/material datepicker components，to maintain consistency.

**Comment by Tian-Hun** [comment]
@Agranom Hi, Interested in merging my PR?

**Comment by Agranom** [comment]
@Tian-Hun Hi, Thanks for you efforts, but I cannot merge it. I tested it and it doesn't work propeply (scroll doesn't work when picker is opened).

**Pull request closed without merging**
