### PR TITLE
Angular 8 upgrade

### PR DESCRIPTION
**Pull request by thduttonuk**

### CODE REVIEW

**Comment by jpike88** [comment]
@Agranom you closed https://github.com/Agranom/ngx-material-timepicker/issues/148, but this pr is still open...

**Comment by jpike88** [comment]
looks good to me, what's blocking this?

**Comment by Agranom** [comment]
I'm just working on a feature. And I will merge this PR right after feature implementation

**Comment by thduttonuk** [comment]
@Agranom let me know if you need any changes on this PR.

**Comment by Agranom** [comment]
@thduttonuk could you please resolve conflicts ?

**Comment by thduttonuk** [comment]
@Agranom I did a rebase, not sure if that was the best idea.

**Comment by jpike88** [comment]
works for me

**Pull request merged**
